@startuml
!theme plain
hide circle
top to bottom direction
!pragma useVerticalIf on
skinparam dpi 350
skinparam packageStyle rectangle
skinparam rectangle {
  BackgroundColor #f7f4eb
  BorderColor Black
}

' === DDD DEFINITIONS ===
!define ENTITY(e) class e <<Entity>>
!define AGGREGATE(a) class a <<Aggregate>>
!define AGGREGATE_ROOT(ar) class ar <<Aggregate Root>>
!define VALUE_OBJECT(vo) class vo <<Value Object>>
!define ENUM(enum) class enum <<Enum>>

title Envision Ad Platform - Domain Driven Design Domain Model

' ===============================
' Media
' ===============================
package ""{
    Skills
    Projects
    Work experience
    Education
    Resume
    Contact information
    Hobbies
    Testimonials
    Messages
}

package "Media Subdomain" #LightGreen {
  AGGREGATE_ROOT(Media) #LightBlue {
    title: String
    estimatedDailyViews: Int
    pricePerHour: Decimal
    width: Decimal
    height: Decimal
    resolution: Decimal
    image: URL
    mediaCorners: double[4]
  }

  note right of Media::height
    Width and height are in CM.
  end note

  ENTITY(MediaType) #LightBlue {
    name: String
    description: String
  }

  VALUE_OBJECT(MediaTypeIdentifier) #Bisque {
    mediaTypeId: UUID
  }

  ENUM(ApprovalStatus) #Orange {
    PENDING
    REJECTED
    APPROVED
  }

  ENUM(ListingStatus) #Orange {
    DRAFT
    LISTED
    UNLISTED
  }

  VALUE_OBJECT(MediaIdentifier) #Bisque {
    mediaId: UUID
  }

  AGGREGATE(MediaLocation) #LightBlue {
    name: String
    description: String
    country: String
    province: String
    city: String
    postalCode: String
    latitude: Float
    longitude: Float
  }

  VALUE_OBJECT(MediaLocationIdentifier) #Bisque {
      mediaLocationId: UUID
}

  MediaType "1" o--> "1" MediaTypeIdentifier
  Media "1" o--> "1" MediaIdentifier
  Media "1" o--> "1" MediaTypeIdentifier
  Media "1" o--> "1" ListingStatus
  Media "1" o--> "1" ApprovalStatus
  MediaLocation "1" o--> "*" "MediaIdentifier"
  MediaLocation "1" o--> "1" "MediaLocationIdentifier"
}

@enduml
